spring:
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/test?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
          driverClassName: com.mysql.cj.jdbc.Driver
          username: root
          password: benny123
        slave:
          url: jdbc:mysql://localhost:3306/test2?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
          driverClassName: com.mysql.cj.jdbc.Driver
          username: root
          password: benny123
server:
  port: 8081

mybatis:
  mapperLocations: classpath:mapper/*.xml
#  typeAliasesPackage: cn.com.benny.learn.dynamic.datasource