package cn.com.benny.learn.generator.model;

import java.util.Date;

public class Student1 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_1.id
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_1.name
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_1.age
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_1.gender
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_1.birthday
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_1.no
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_1.other
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    private String other;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_1.id
     *
     * @return the value of student_1.id
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_1.id
     *
     * @param id the value for student_1.id
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_1.name
     *
     * @return the value of student_1.name
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_1.name
     *
     * @param name the value for student_1.name
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_1.age
     *
     * @return the value of student_1.age
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_1.age
     *
     * @param age the value for student_1.age
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_1.gender
     *
     * @return the value of student_1.gender
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_1.gender
     *
     * @param gender the value for student_1.gender
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_1.birthday
     *
     * @return the value of student_1.birthday
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_1.birthday
     *
     * @param birthday the value for student_1.birthday
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_1.no
     *
     * @return the value of student_1.no
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_1.no
     *
     * @param no the value for student_1.no
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_1.other
     *
     * @return the value of student_1.other
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_1.other
     *
     * @param other the value for student_1.other
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }
}