package cn.com.benny.learn.mybatis.generator.mapper;

import cn.com.benny.learn.mybatis.generator.model.Student1;
import cn.com.benny.learn.mybatis.generator.model.Student1Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;



public interface Student1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_1
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    int countByExample(Student1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_1
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    int deleteByExample(Student1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_1
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_1
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    int insert(Student1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_1
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    int insertSelective(Student1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_1
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    List<Student1> selectByExampleWithBLOBs(Student1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_1
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    List<Student1> selectByExample(Student1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_1
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    Student1 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_1
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    int updateByExampleSelective(@Param("record") Student1 record, @Param("example") Student1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_1
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Student1 record, @Param("example") Student1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_1
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    int updateByExample(@Param("record") Student1 record, @Param("example") Student1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_1
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    int updateByPrimaryKeySelective(Student1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_1
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Student1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_1
     *
     * @mbggenerated Tue Nov 06 11:28:42 CST 2018
     */
    int updateByPrimaryKey(Student1 record);
}